services:
  skywalking-oap:
    image: skywalking.docker.scarf.sh/apache/skywalking-oap-server:9.5.0
    container_name: skywalking-oap
    environment:
      SW_STORAGE: elasticsearch
      SW_STORAGE_ES_CLUSTER_NODES: elasticsearch:9200
      SW_CORE_RECORD_DATA_TTL: 7
      SW_CORE_METRICS_DATA_TTL: 7
      SW_HEALTH_CHECKER: default
      SW_TELEMETRY: prometheus
      SW_TELEMETRY_PROMETHEUS_HOST: 0.0.0.0
      SW_TELEMETRY_PROMETHEUS_PORT: 1234
      JAVA_OPTS: "-Xms256m -Xmx512m"
    ports:
      - "11800:11800"
      - "12800:12800"
      - "1234:1234"
    networks:
      - doj

  skywalking-ui:
    image: apache/skywalking-ui:9.5.0
    container_name: skywalking-ui
    depends_on:
      - skywalking-oap
    environment:
      SW_OAP_ADDRESS: http://skywalking-oap:12800
    ports:
      - "9999:8080"
    networks:
      - doj

networks:
  doj:
    external: true
